services:
  pg:
    image: postgres:18-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - tasks-psql-data:/var/lib/psql
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskdb

volumes:
  tasks-psql-data:
