# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  runner-job:
    name: Build and test Go
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ vars.POSTGRES_USERNAME }}
          POSTGRES_DB: tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    
    - name: Setup Go 1.25.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.x'

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        DBHOST: localhost
        DBUSER: ${{ vars.POSTGRES_USERNAME }}
        DBPASS: ${{ vars.POSTGRES_PASSWORD }}
        DBPORT: "5432"
        DBNAME: tests
        KEYCLOAK_SERVER_URL: ${{ vars.KEYCLOAK_SERVER_URL }}
        KEYCLOAK_REALM: ${{ vars.KEYCLOAK_REALM }}
        KEYCLOAK_CLIENT_ID: ${{ vars.KEYCLOAK_CLIENT_ID }}
        KEYCLOAK_CLIENT_SECRET: ${{ vars.KEYCLOAK_CLIENT_SECRET }}
      run: go test -v ./...