# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:20-bookworm-slim

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go 1.25.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.x'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
      env:
          DBHOST: postgres
          DBUSER: postgres
          DBPORT: 5432
          DBPASS: 1234
          DBNAME: tests
